language: python
python:
  - "2.7"
install: 
  - "pip install -r requirements.txt --use-mirrors"
  - "pip install -r test-requirements.txt --use-mirrors"
  - ./scripts/install_jscover.sh
  - "pip install coveralls"
  - "python setup.py install"
script:
  - "coverage run -m nose"
  - "coverage run `which lettuce` js_test_tool/features"
after_success:
  - coveralls
