sudo: false
language: python
cache: pip
python:
  - "2.7"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
install: 
  - "pip install -r requirements.txt --use-mirrors"
  - "pip install -r test-requirements.txt --use-mirrors"
  - ./scripts/acceptance_reqs.sh
  - "pip install coveralls"
  - "python setup.py install"
script:
  - "coverage run -p -m nose"
  - "coverage run -p `which lettuce` js_test_tool/features"
after_success:
  - "coverage combine"
  - coveralls
